### ISSUE TITLE
Duplicate definition error in VS 2022

### ISSUE THREAD

**Issue by Dimension4** [manuelroemer/IsExternalInit#10] opened 2021-11-11 10:29 UTC
I'm trying to upgrade my solution to VS 2022, but if I build it I'm getting duplicate definition errors that weren't there before with VS 2019. I guess this is caused by the new .net 6 sdk?

I think a simple future proof fix would be to wrap the source code in another #if block
```cs
#if !NET
...
#endif
```
since `NET` is defined for .net 5 and later.

**Comment by i2van** [comment] 2021-11-14 23:35
\+

**Comment by manuelroemer** [comment] 2021-11-15 13:00
Hey, I tried to reproduce the issue but cannot, at the moment. I created a new console app, added the package and the following code:

```cs
Console.WriteLine(new Message("Hello, World!"));

public record Message(string Mesage);
```
So far, everything works on my side. I successfully ran it using the `netcoreapp3.1`, `net5.0` and `net6.0` TFMs. I'm at .NET `6.0.100` and VS `17.1.0 Preview 1.0` (I only have the preview version installed right now, maybe it is that?).

Could you maybe upload a minimal example project which causes issues for you? Thanks a lot!

**Comment by Dimension4** [comment] 2021-11-15 14:43
We're multi targeting .net framework 4.5.2, 4.8 and .net core 3.1. I can't do more testing at the moment because I had to uninstall VS 2022 since it also broke the builds on VS 2019.

**Comment by SWeini** [comment] 2021-11-15 15:52
I installed the .NET 6 SDK (no VS 2022 yet) and this makes my compilation fail as well. The project is a WPF project (`UseWPF=true`). Works like a charm when removing the Workaround from the `.targets` file.

Looks like they changed something in .NET 6, see https://github.com/dotnet/wpf/issues/810

**Comment by manuelroemer** [comment] 2021-11-15 16:38
Yeah, it seems like something in the SDK/tooling changed/got broken.
Not sure how to tackle this generally, but in the meantime I am totally happy with conditionally excluding the file's content via the proposed `NET` toggle. That might fix some of the issues without being a problem in the future. @i2van I uploaded a new package for testing it: [`1.0.2-pre1`](https://www.nuget.org/packages/IsExternalInit/1.0.2-pre1).

In any case, if something is wrong with the SDK, there is not much I can do at the moment. I also don't have any time for investigating where the issue is rooted. Either someone else has an idea/makes a PR for this repo or the issue gets fixed upstream by the .NET guys.

> Works like a charm when removing the Workaround from the .targets file.

@SWeini That's an interesting clue, thanks a lot! Just to clarify, do you mean [these definitions here](https://github.com/manuelroemer/IsExternalInit/blob/master/src/IsExternalInit/IsExternalInit.netstandard2.0.targets)? If these are an issue, we could **_maybe_** remove them altogether (I think the issue that they worked around was eventually fixed in some .NET 5 SDK update).

**Comment by i2van** [comment] 2021-11-15 17:14
@manuelroemer It doesn't compile with new package out of the box. Looks like `global.json` `sdk.version` setting also matter. Adding file locally solves issues for both VS 2019 and 2022. [Project](https://github.com/i2van/CsvLINQPadDriver) I mentioned also uses WPF and has builds for 4.61, .NET Core 3.1, .NET 5/6

**Comment by i2van** [comment] 2021-11-15 17:23
`global.json.sdk.version` version with new package under VS 2022:

| .NET |  Result |
|-|-|
| 5.0.400 | OK |
| 6.0.100 | Error CS0101: The namespace 'System.Runtime.CompilerServices' already contains a definition for 'IsExternalInit' |

**Comment by SWeini** [comment] 2021-11-16 09:48
I tried to fix it referencing the MSBuild property that is used in the background. See #11.

**Comment by SWeini** [comment] 2021-11-16 11:12
We could also remove the .targets files completely. That's how the issue seems to be solved in https://github.com/manuelroemer/Nullable
Use .NET 5 SDK and set `IncludePackageReferencesDuringMarkupCompilation` to `true` or use .NET 6 SDK and use `true` by default.

If you want to be backwards-compatible to SDKs before .NET 5 you might still need that workaround. I haven't tested this with all possible versions.

> @SWeini That's an interesting clue, thanks a lot! Just to clarify, do you mean [these definitions here](https://github.com/manuelroemer/IsExternalInit/blob/master/src/IsExternalInit/IsExternalInit.netstandard2.0.targets)? If these are an issue, we could **_maybe_** remove them altogether (I think the issue that they worked around was eventually fixed in some .NET 5 SDK update).

**Comment by manuelroemer** [comment] 2021-11-16 11:20
> We could also remove the .targets files completely. [...] If you want to be backwards-compatible to SDKs before .NET 5 you might still need that workaround.

Yes, I think that removing the workaround is the best course of action. And I think the assumption that users have an up-to-date SDK (be it .NET 5 or .NET6+) is reasonable enough. Would you like to make this change in your PR? Would be much appreciated! 🍻 
(Thanks for opening your current PR, by the way!)

**Comment by i2van** [comment] 2021-11-16 11:26
Could you upload package for testing, please?

**Comment by manuelroemer** [comment] 2021-11-16 11:27
You mean with the change proposed by @SWeini? If so, yes, I'd upload a prerelease for testing before creating a "full" release.

**Comment by Dimension4** [comment] 2021-11-22 08:05
@manuelroemer sorry for bumping this, but what's the plan now? I see there's a PR waiting for approval, is there anything that needs to be done?

**Comment by manuelroemer** [comment] 2021-11-22 16:58
> @manuelroemer sorry for bumping this, but what's the plan now? 

No worries, bumping is more than fair here! I merged #11 and uploaded the next prerelease version for testing: https://www.nuget.org/packages/IsExternalInit/1.0.2-pre2

If that still doesn't make things work, my last remaining hope is to revert #5, but my hope is to avoid that.

**Comment by Dimension4** [comment] 2021-11-23 08:39
@manuelroemer can confirm it works for me now 👍

**Comment by Dimension4** [comment] 2021-11-23 10:50
Will the fix be released as a proper version 1.0.2 or do we keep the 1.0.2-pre2 tag? Just so I know when to merge back into master in our code base :)

**Comment by i2van** [comment] 2021-11-23 11:25
Works for me.

**Comment by manuelroemer** [comment] 2021-11-23 12:09
> Will the fix be released as a proper version 1.0.2 or do we keep the 1.0.2-pre2 tag?

I'll release a 1.0.2 very soon!

**Comment by manuelroemer** [comment] 2021-11-23 12:32
Done. Thanks to all of you for helping resolve this issue!

**Closed by manuelroemer** 2021-11-23 12:32 UTC

**Comment by Dimension4** [comment] 2021-11-23 12:54
Thanks for providing and updating the package!

**Comment by Dimension4** [comment] 2021-11-23 13:31
I think we've broken the old behavior now. If you try to use the new nuget package without having .net 6 sdk installed, builds break on VS 2019 with the same error
> Error CS0518: Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported

**Comment by Dimension4** [comment] 2021-11-23 14:28
Ok it looks like it's not really broken, but the behavior changed a bit. Previously, we were able to just reference the nuget package (with .net 5) and it just worked. But now we also have to add

    <IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>

to make it work with .net 5. So now I can confirm it works with .net 6 as well as .net 5. 

Sorry for the confusion 😅

**Comment by johanneshoehn** [comment] 2021-12-13 19:09
@manuelroemer 1.0.1 is still the newest version on nuget.org. Was the 1.0.2 pulled, or something?

**Comment by i2van** [comment] 2021-12-13 19:14
> @manuelroemer 1.0.1 is still the newest version on nuget.org. Was the 1.0.2 pulled, or something?

https://www.nuget.org/packages/IsExternalInit/1.0.2

**Comment by manuelroemer** [comment] 2021-12-14 11:55
Hey, as @i2van said, it was unlisted, probably by accident when I unlisted the prerelease versions. In any case the full 1.0.2 is back now.
