### ISSUE TITLE
Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported

### ISSUE THREAD

**Issue by TheRealAyCe** [manuelroemer/IsExternalInit#12] opened 2022-05-17 19:27 UTC
When using the package I get this error with my records. (net461/netstandard2.0/netstandard2.1)

But additonally using
```
namespace System.Runtime.CompilerServices
{
    internal class IsExternalInit { }
}
```
will show that this is already included by the package.

When I build the solution by starting a project within the solution that references the project using IsExternalInit, it compiles. But when I compile the standalone project it shows this error for each record.

It used to work not too long ago, but now it doesn't, very strange. I'm using VS 17.2 and 17.3 Preview.

Only using my own IsExternalInit works every time, but I would like to use the package...

**Comment by manuelroemer** [comment] 2022-05-18 06:43
Hey, thanks for reporting the issue! Could you perhaps attach a solution which allows me to reproduce the problem? That (should) make it easier for me to troubleshoot it.

**Comment by TheRealAyCe** [comment] 2022-05-18 12:17
It's related to this problem: https://github.com/dotnet/sdk/issues/24124?notifications_query=issuecomment-1072738722#issuecomment-1072738722

When I put the `global.json` I mention there in the solution folder, it works, presumably because 6.0.103 still works on Windows 7. When I remove it the weird errors occur. This could also explain why it seems to work when the build is started by a legacy csproj-format project, afaik the old csproj-format is using MSBuild and not `dotnet`.

I think there is an internal failure where the .cs file from the package is not correctly added to the compilation with `dotnet` >6.0.103 under Windows 7. Probably nothing you can do something about.

The solution for me is to either not use the package, or put a `global.json` with a version that still works on Windows 7. Referencing a package that comes with its own public `IsExternalInit` (not .cs file) works too.

**Comment by manuelroemer** [comment] 2022-06-02 10:54
Thanks a lot for the additional details! I think that I am going to close the issue then for the moment. If this does turn out to be a different issue, feel free to reopen it/create a new one!

Just a note: Both this package and the `Nullable` package seem to have some issues in the latest .NET SDK on newer OSs. Maybe this is also related to the issue you are describing here. In any case, we will have to wait until we find out what the issue is exactly there.

**Closed by manuelroemer** 2022-06-02 10:54 UTC
